name: Test Basic Versioning

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-basic-version:
    runs-on: ubuntu-latest
    name: Test Basic Version Generation
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true
    
    - name: Test Basic Version
      id: version
      uses: sanjeevkumarraob/version-system@v1
      with:
        VERSION_FILE: "version.txt"
        GIT_REPO_PATH: "."
        CREATE_RELEASE: false
        IS_SNAPSHOT: false
    
    - name: Display Results
      run: |
        echo "🏷️ Current Version: ${{ steps.version.outputs.current_version }}"
        echo "🚀 Next Version: ${{ steps.version.outputs.version }}"
    
    - name: Validate Output
      run: |
        if [[ "${{ steps.version.outputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "✅ Basic version format is valid: ${{ steps.version.outputs.version }}"
        else
          echo "❌ Error: Invalid basic version format: ${{ steps.version.outputs.version }}"
          exit 1
        fi
